config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :beer_styles, except: [:show]
    resources :breweries, except: [:show]
    resources :members, except: [:new, :create] do
      get "followings" => "relationships#followings"
      get "followers" => "relationships#followers"
      get "group_list" => "groups#group_list"
    end
    resources :posts, except: [:new, :create] do
      resources :post_comments, only: [:destroy]
    end
    resources :beers
    resources :bars, only: [:index, :create, :destroy]
    resources :groups, except: [:new, :create] do
      resources :group_posts, except: [:new, :create] do
        resources :group_post_comments, only: [:destroy]
      end
    end
  end

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
    resources :beers, except: [:edit, :update, :destroy]
    resources :posts do
      resource :cheer, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :bars, only: [:create]
    resources :members, only: [:update, :index, :show] do
      resource :relationship, only: [:create, :destroy]
      get "followings" => "relationships#followings"
      get "followers" => "relationships#followers"
    end
    resources :groups do
      resource :groups_member, only: [:create, :destroy]
      resources :group_posts do
        resources :group_post_comments, only: [:create, :destroy]
      end
    end
    resources :message_rooms, only: [:create, :show, :index] do
     resource :entry, only: [:create]
     resources :messages, only: [:create, :destroy]
    end
    devise_scope :member do
      post "guest_sign_in", to: "members/sessions#guest_sign_in"
    end
    get "mypage" => "homes#timeline"
    get "mypage/cheers_list" => "homes#cheers_list"
    get "mypage/group_list" => "homes#group_list"
    get "mypage/edit" => "members#edit"
  end

  root "public/homes#top"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :member
  belongs_to :follow, class_name: "Member"
end

app/controllers/admin/relationships_controller.rb
class Admin::RelationshipsController < ApplicationController
  before_action :set_member
  layout "application_no_sidebar"

  def followings
    member_search = params[:member_search]
    # 会員検索で受け取った値を代入
    unless member_search.nil?
      @members = @member.followings.where("account_name like ?", "%#{member_search}%").page(params[:page]).per(10)
    else
      @members = @member.followings.page(params[:page]).per(10)
    end
  end

  def followers
    member_search = params[:member_search]
    # 会員検索で受け取った値を代入
    unless member_search.nil?
      @members = @member.followers.where("account_name like ?", "%#{member_search}%").page(params[:page]).per(10)
    else
      @members = @member.followers.page(params[:page]).per(10)
    end
  end

  def set_member
    @member = Member.find(params[:member_id])
  end
end

app/helpers/admin/relationships_helper.rb
module Admin::RelationshipsHelper
end

app/views/admin/relationships/followers.html.erb
<div class="col-md-10 mx-auto">
  <%= render "admin/members/show", member: @member %>

  <div class="form-row mt-3 d-flex justify-content-end mr-1">
    <%= form_with url: admin_member_followers_path, method: :get, local: false do |f| %>
    <div class="input-group border border-secondary rounded-pill bg-white mb-1">
      <%= f.text_field :member_search, placeholder: "アカウント名で検索", class: "form-control form-control-sm input-group-prepend border-0 bg-transparent" %>
      <span class="input-group-btn">
       <%= f.button type: "submit",class: "border-0 form-control form-control-sm bg-transparent" do %><i class="fas fa-search"></i><% end %>
      </span>
    </div>
    <% end %>
  </div>

  <div class="col">
    <u><%= link_to "フォロー",admin_member_followings_path(member_id: params[:member_id]), class: "mr-2 text-reset" %></u>
    <span class="mr-2">|</span>
    <h5 class="d-inline-block font-weight-bold">フォロワー</h6>
  </div>

  <% if @member.followers.exists? %>
    <div id="followers-index">
      <%= render "admin/members/index", members: @members %>
    </div>

  <% else %>
    <div class="text-center mt-3">
      <span>フォロワーがいません<span>
    </div>
  <% end %>
</div>

app/views/admin/relationships/followers.js.erb
$("#followers-index").html("<%= j(render "public/members/index", members: @members) %>");

app/views/admin/relationships/followings.html.erb
<div class="col-md-10 mx-auto">
  <%= render "admin/members/show", member: @member %>

  <div class="form-row mt-3 d-flex justify-content-end mr-1">
    <%= form_with url: admin_member_followings_path, method: :get, local: false do |f| %>
    <div class="input-group border border-secondary rounded-pill bg-white mb-1">
      <%= f.text_field :member_search, placeholder: "アカウント名で検索", class: "form-control form-control-sm input-group-prepend border-0 bg-transparent" %>
      <span class="input-group-btn">
       <%= f.button type: "submit",class: "border-0 form-control form-control-sm bg-transparent" do %><i class="fas fa-search"></i><% end %>
      </span>
    </div>
    <% end %>
  </div>


  <div class="col">
    <h5 class="mr-2 d-inline-block font-weight-bold">フォロー</h6>
    <span class="mr-2">|</span>
    <u><%= link_to "フォロワー",admin_member_followers_path(member_id: params[:member_id]), class: "text-reset" %></u>
  </div>

  <% if @member.followings.exists? %>
    <div id="followings-index">
      <%= render "admin/members/index", members: @members %>
    </div>

  <% else %>
  <div class="text-center mt-3">
    <span>フォローしているユーザーがいません<span>
    <% if @member == current_member %>
      <br><u><%= link_to "ユーザーを探してフォローしましょう！", members_path, class: "text-reset" %></u>
    <% end %>
  </div>
  <% end %>
</div>

app/views/admin/relationships/followings.js.erb
$("#followings-index").html("<%= j(render "public/members/index", members: @members) %>");