config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :beer_styles, except: [:show]
    resources :breweries, except: [:show]
    resources :members, except: [:new, :create] do
      get "followings" => "relationships#followings"
      get "followers" => "relationships#followers"
      get "group_list" => "groups#group_list"
    end
    resources :posts, except: [:new, :create] do
      resources :post_comments, only: [:destroy]
    end
    resources :beers
    resources :bars, only: [:index, :create, :destroy]
    resources :groups, except: [:new, :create] do
      resources :group_posts, except: [:new, :create] do
        resources :group_post_comments, only: [:destroy]
      end
    end
  end

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
    resources :beers, except: [:edit, :update, :destroy]
    resources :posts do
      resource :cheer, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :bars, only: [:create]
    resources :members, only: [:update, :index, :show] do
      resource :relationship, only: [:create, :destroy]
      get "followings" => "relationships#followings"
      get "followers" => "relationships#followers"
    end
    resources :groups do
      resource :groups_member, only: [:create, :destroy]
      resources :group_posts do
        resources :group_post_comments, only: [:create, :destroy]
      end
    end
    resources :message_rooms, only: [:create, :show, :index] do
     resource :entry, only: [:create]
     resources :messages, only: [:create, :destroy]
    end
    devise_scope :member do
      post "guest_sign_in", to: "members/sessions#guest_sign_in"
    end
    get "mypage" => "homes#timeline"
    get "mypage/cheers_list" => "homes#cheers_list"
    get "mypage/group_list" => "homes#group_list"
    get "mypage/edit" => "members#edit"
  end

  root "public/homes#top"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member
  belongs_to :beer
  belongs_to :bar, optional: true
  belongs_to :shop, class_name: "Bar", optional: true
  has_many :cheers, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :cheers_members, through: :cheers, source: :member

  has_one_attached :post_image

  validates :content, length: { maximum: 500 }
  validates :serving_style, presence: true

  enum serving_style: { draft: 0, can: 1, bottle: 2, others: 3 }, _prefix: true

  def get_post_image(width, height)
    unless post_image.attached?
      file_path = Rails.root.join("public/images/post-no-image.jpg")
      post_image.attach(io: File.open(file_path), filename: "post-default-image.jpg", content_type: "image/jpeg")
    end
    post_image.variant(resize_to_fit: [width, height]).processed
  end

  # 既にcheersしているかを
  def cheers_already?(member)
    cheers.exists?(member_id: member.id)
  end

  # 投稿に紐づくビールの評価を再計算し、再代入
  def reevaluate_beer
    self.beer.update(evaluation: self.beer.beer_evaluation)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  layout "application_no_sidebar"

  def index
    post_search = params[:post_search]
    # 投稿検索で受け取った値を代入
    unless post_search
      @posts = Post.all.order(id: :desc).page(params[:page]).per(7)
    else
      @posts = Post.where("content like ?", "%#{post_search}%").order(id: :desc).page(params[:page]).per(7)
    end
  end

  def show
    @post_comment = PostComment.new
    @post_comments = @post.post_comments.order("id DESC").page(params[:page]).per(5)
  end

  def edit
    @beer = @post.beer
    @bar = Bar.new
    @bars = Bar.where(category: 0)
    @shops = Bar.where(category: 1)
  end

  def update
    if @post.update(post_params)
      evaluation = @post.beer.beer_evaluation
      @post.beer.update(evaluation: evaluation)
      redirect_to admin_posts_path, success: "管理者権限で投稿を更新しました"
    else
      render "error"
    end
  end

  def destroy
    @post.update(evaluation: nil)
    # 削除する投稿のevaluationをnilにする（=この後の計算の分母・分子から除く）
    evaluation = @post.beer.beer_evaluation
    @post.beer.update(evaluation: evaluation)
    @post.destroy
    redirect_to admin_posts_path, alert: "管理者権限で投稿を削除しました"
  end

  private
    def post_params
      params.require(:post).permit(:member_id, :beer_id, :bar_id, :shop_id, :content, :evaluation, :serving_style, :post_image)
    end

    def set_post
      @post = Post.find(params[:id])
    end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_index.html.erb
<% if posts.present? %>

  <% posts.each do |post| %>
  <div class="card border-dark mt-2 shadow">
    <div class="row no-gutters">
      <div class="col-md-2">
        <%= link_to admin_post_path(post) do %>
          <%= image_tag post.get_post_image(540,540), class: "image-fit" %>
        <% end %>
      </div>
      <div class="card-body d-flex flex-column col-md-10 pt-2 pl-4 pr-4 pb-3">
        <%= render "admin/posts/post_deteil", post: post %>
      </div>
    </div>
  </div>
  <% end %>

  <div class="d-flex justify-content-center mt-2">
    <%= paginate posts %>
  </div>

<% else %>
  <div class="text-center mt-3">
    <span>投稿がありません<span>
  </div>
<% end %>

app/views/admin/posts/_post_deteil.html.erb
<div class="row card-text border-bottom mb-0 d-flex align-items-center">
  <%= image_tag post.member.get_member_image(50,50), class: "rounded-circle image-fit" %>
  <h6 class="ml-1 mb-0"><%= link_to post.member.display_name, admin_member_path(post.member), class: "text-reset" %></h6>
  <span class="small ml-2"><%= post.created_at.to_s(:datetime_jp) %></span>
  <div class="flex-grow-1 text-right small mr-2">
    <%= link_to "編集", edit_admin_post_path(post), class: "text-secondary" %>
    <%= link_to "削除", admin_post_path(post), method: :delete, remote: true, "data-confirm" => "本当に削除しますか？", class: "text-secondary text-right" %>
  </div>
</div>

<div class="row">
  <div class="mt-1 mb-0 card-title">
    <%# ビール名部分 %>
    <h5 class="font-weight-bold d-inline-block mb-0">
      <%= link_to post.beer.name, admin_beer_path(post.beer), class: "text-reset" %></h5>


    <%# ブルワリー名部分 %>
    <h6 class="d-inline-block mb-0">
      <span class="ml-1">/</span>
      <%= post.beer.brewery.name %>
    </h6>
  </div>
</div>

<div class="row align-items-center d-flex px-0">
  <%# レビュー部分 %>
  <% unless post.evaluation %>
    <span>未評価</span>
  <% else %>
    <span id="stars-rate<%= post.id %>">
      <%= render "public/posts/post_rate_display", post: post %>
    </span>
    <h5 class="font-weight-bold mx-2 mb-0"><%= post.evaluation %></h5>
  <% end %>

  <div class="small mt-auto">
    <%# サービング部分 %>
    <span>（Served</span>
    <span>
      <% if post.serving_style == "draft" %>on
      <% else %>by
      <% end %>
    </span>
    <span>
      <% if post.serving_style_draft? %>
        <i class="fas fa-beer"></i>ドラフト）
      <% elsif post.serving_style_can? %>
        <i class="fas fa-database"></i>缶）
      <% elsif post.serving_style_bottle? %>
        <i class="fas fa-wine-bottle"></i>ボトル）
      <% else %>
        <i class="fas fa-question"></i></i>その他）
      <% end %>
    </span>
  </div>
</div>

<div class="row d-flex">
  <%# 本文/一覧画面では40文字以上表示されないようにする %>
  <% if current_page?(admin_post_path(post)) %>
    <span><%= post.content %></span>
  <% else %>
    <span>
      <%= post.content.truncate(40) %>
      <% if post.content.size > 40 %>
        <span class="text-secondary">
          <%= link_to "続きを読む", admin_post_path(post), class: "text-reset" %>
        </span>
      <% end %>
    </span>
  <% end %>
</div>

<div class="row small mt-auto pt-1">
  <%# Cheers部分 %>
  <span class="text-dark font-weight-bold">
    <i class="fas fa-glass-cheers fa-lg"></i>
    <%= post.cheers.count %>Cheers
  </span>
  <span class="ml-1">|</span>

  <div>
    <%# コメント部分/詳細画面ではリンクを外す %>
    <span class="ml-1">
      <% if current_page?(admin_post_path(post)) %>
        コメント<%= post.post_comments.count %>件
      <% else %>
        <%= link_to admin_post_path(post), class: "text-reset" do %>
          <i class="fas fa-comments"></i>
          コメント<%= post.post_comments.count %>件
        <% end %>
      <% end %>
    </span>
  </div>

  <%# お店情報部分 %>
  <% unless post.bar.nil? %>
    <span class="ml-1">|</span>
    <span class="ml-1">
      飲んだお店：<%= post.bar.place_name %>
    </span>
  <% end %>
  <% unless post.shop.nil? %>
    <span class="ml-1">|</span>
    <span class="ml-1">
      買ったお店：<%= post.shop.place_name %>
    </span>
  <% end %>
</div>

app/views/admin/posts/_post_form.html.erb
<div id="error-message">
  <%= render "layouts/errors", obj: @beer %>
</div>

<div class="row form-group my-2">
  <div class="col-md-3">
    <span>投稿者</span>
  </div>
  <div class="col-md-9">
    <span>
      <%= post.member.display_name %>（アカウント名：<%= post.member.account_name %>）
    </span>
  </div>
</div>

<div class="row form-group my-2">
  <div class="col-md-3">
    <span>ビール名</span>
  </div>
  <div class="col-md-9">
    <span><%= beer.name %></span>
  </div>
</div>


  <%= form_with model: [:admin, post], local: false do |f| %>
    <%= f.hidden_field :beer_id, :value => beer.id %>
    <div class="row form-group my-2">
      <div class="col-md-3">
        <%= f.label :post_image, "画像", class: "col-form-label" %>
      </div>
      <div class="col-md-9 d-flex align-items-center">
        <%= f.file_field :post_image, accept: "image/*", class: "form-control-file" %>
      </div>
    </div>

    <div class="row form-group my-2">
      <div class="col-md-3">
         <%= f.label :evaluation, "評価", class: "col-form-label" %>
      </div>
      <div class="col-md-9 d-flex align-items-center", id="stars">
      </div>
    </div>

    <div class="row form-group my-2">
      <div class="col-md-3">
         <%= f.label :serving_style, "サービング", class: "col-form-label" %><span class="text-danger">*</span>
      </div>
      <div class="col-md-9 form-control border-0">
        <div class="form-check form-check-inline">
          <%= f.radio_button :serving_style, :draft, class: "form-check-input" %>
          <%= f.label :serving_style_draft, "ドラフト", class: "form-check-label" %>
        </div>
        <div class="form-check form-check-inline">
          <%= f.radio_button :serving_style, :can, class: "form-check-input" %>
          <%= f.label :serving_style_can, "缶", class: "form-check-label" %>
        </div>
        <div class="form-check form-check-inline">
          <%= f.radio_button :serving_style, :bottle, class: "form-check-input" %>
          <%= f.label :serving_style_bottle, "ボトル", class: "form-check-label" %>
        </div>
        <div class="form-check form-check-inline">
          <%= f.radio_button :serving_style, :others, class: "form-check-input" %>
          <%= f.label :serving_style_others, "その他", class: "form-check-label" %>
        </div>
      </div>
    </div>

    <div class="row form-group my-2">
      <div class="col-md-3">
        <%= f.label :content, "キャプション", class: "col-form-label" %>
      </div>
      <div class="col-md-9">
        <%= f.text_area :content, autofocus: true, rows: 5, placeholder: "飲んだ感想などを自由に記入してください！（省略可）", class: "form-control" %>
      </div>
    </div>

    <div id="bars-and-shops">
     <%= render "public/posts/bars_and_shops", bars: @bars, shops: @shops, f: f %>
    </div>

    <div class="actions text-center py-3">
      <% if params[:id] == nil %>
        <%= f.submit "投稿", class: "btn btn-success px-4 rounded-pill" %>
      <% else %>
        <%= f.submit "更新", class: "btn btn-success px-4 rounded-pill" %>
      <% end %>
      <%= link_to "戻る", :back, class: "btn btn-primary px-4 rounded-pill" %>
    </div>
  <% end %>

<script>
  $('#stars').empty();
  $("#stars").raty({
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    scoreName: 'post[evaluation]',
    half: true,
    <% if post.evaluation != nil %>
      score: <%= post.evaluation %>,
      readOnly: false,
    <% end %>
  });
  </script>

app/views/admin/posts/_post_search.html.erb
<div class="form-row mt-3 d-flex justify-content-end mr-1">
  <%= form_with url: admin_posts_path, method: :get, local: false do |f| %>
  <div class="input-group border border-secondary rounded-pill bg-white mb-1">
    <%= f.text_field :post_search, placeholder: "投稿を検索", class: "form-control form-control-sm input-group-prepend border-0 bg-transparent" %>
    <span class="input-group-btn">
     <%= f.button type: "submit",class: "border-0 form-control form-control-sm bg-transparent" do %><i class="fas fa-search"></i><% end %>
    </span>
  </div>
  <% end %>
</div>

app/views/admin/posts/edit.html.erb
<div class="row">
  <div class="card border-dark mx-auto mt-3 col-md-10">
    <div class="card-body">
      <div class="d-flex border-bottom align-items-end pb-1 mb-3">
        <h5 class="card-title mb-0">投稿編集</h5>
        <span class="small text-danger mb-0 ml-1">*は必須項目です</span>
      </div>
      <%= render "post_form", post: @post, beer: @beer, bar: @bar, shop: @shop, bars: @bars, shops: @shops %>
    </div>
  </div>
</div>

app/views/admin/posts/index.html.erb
<div class="col-md-10 mx-auto">
  <%= render "post_search" %>
  <div id="posts-index">
    <%= render "index", posts: @posts %>
  </div>
</div>

app/views/admin/posts/index.js.erb
$("#posts-index").html("<%= j(render "admin/posts/index", posts: @posts) %>");

app/views/admin/posts/show.html.erb
<div class="card border-dark mt-3">
  <div class="row no-gutters">
    <div class="col-md-3 pr-2">
      <%= image_tag @post.get_post_image(250,250), class: "image-fit"  %>
    </div>
    <div class="card-body d-flex flex-column col-md-9 pt-2 px-3">
      <%= render "post_deteil", post: @post %>
    </div>
  </div>
</div>

<% if @post.post_comments.exists? %>
  <div class="card border-dark mt-2 px-2">
    <div id="post-comments-index">
    <%= render "admin/post_comments/post_comments_index", post_comments: @post_comments, post: @post %>
    </div>
  </div>
<% else %>
  <div class="text-center mt-3">
    <span>コメントはありません<span>
  </div>
<% end %>

<div class="d-flex justify-content-center mt-2">
  <%= paginate @post_comments %>
</div>

<div class="text-center">
  <%= link_to "戻る", admin_posts_path, class: "btn btn-primary px-4 rounded-pill" %>
</div>