config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :beer_styles, except: [:show]
    resources :breweries, except: [:show]
    resources :members, except: [:new, :create] do
      get "followings" => "relationships#followings"
      get "followers" => "relationships#followers"
      get "group_list" => "groups#group_list"
    end
    resources :posts, except: [:new, :create] do
      resources :post_comments, only: [:destroy]
    end
    resources :beers
    resources :bars, only: [:index, :create, :destroy]
    resources :groups, except: [:new, :create] do
      resources :group_posts, except: [:new, :create] do
        resources :group_post_comments, only: [:destroy]
      end
    end
  end

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
    resources :beers, except: [:edit, :update, :destroy]
    resources :posts do
      resource :cheer, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :bars, only: [:create]
    resources :members, only: [:update, :index, :show] do
      resource :relationship, only: [:create, :destroy]
      get "followings" => "relationships#followings"
      get "followers" => "relationships#followers"
    end
    resources :groups do
      resource :groups_member, only: [:create, :destroy]
      resources :group_posts do
        resources :group_post_comments, only: [:create, :destroy]
      end
    end
    resources :message_rooms, only: [:create, :show, :index] do
     resource :entry, only: [:create]
     resources :messages, only: [:create, :destroy]
    end
    devise_scope :member do
      post "guest_sign_in", to: "members/sessions#guest_sign_in"
    end
    get "mypage" => "homes#timeline"
    get "mypage/cheers_list" => "homes#cheers_list"
    get "mypage/group_list" => "homes#group_list"
    get "mypage/edit" => "members#edit"
  end

  root "public/homes#top"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/beer.rb
class Beer < ApplicationRecord
  belongs_to :brewery
  belongs_to :beer_style
  has_many :posts, dependent: :destroy
  has_many :purchased_shops, through: :posts, source: :shop
  # 特定のビールが買われたお店のデータを取りに行く
  has_many :drunk_bars, through: :posts, source: :bar
  # 特定のビールが飲まれたお店のデータを取りに行く

  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :abv, numericality: true, allow_nil: true
  validates :ibu, numericality: true, allow_nil: true
  validates :description, length: { maximum: 500 }

  def beer_evaluation
    evaluations_all = self.posts.pluck(:evaluation)
    # beerに紐づけられた投稿のevaluationカラムを配列で取り出す
    evaluations = evaluations_all.compact
    # nilを除く
    evaluations.sum.fdiv(evaluations.length)
    # 平均値を算出
  end
end

app/controllers/admin/beers_controller.rb
class Admin::BeersController < ApplicationController
  before_action :authenticate_admin!
  layout "application_no_sidebar"

  def new
    @beer = Beer.new
    @breweries = Brewery.all
    @beer_styles = BeerStyle.all
  end

  def create
    @beer = Beer.new(beer_params)
    @beer.save ? (redirect_to admin_beer_path(@beer), success: "ビール情報を登録しました") : (render "error")
  end

  def index
    @breweries = Brewery.all
    @beer_styles = BeerStyle.all
    # ビール（キーワード）検索で受け取った値を代入
    @beer_search = params[:beer_search]
    # ブルワリー検索で受け取った値を代入
    @refine_brewery = params[:refine_brewery]
    # ビアスタイル検索で受け取った値を代入
    @refine_beer_style = params[:refine_beer_style]
    if @beer_search != nil
      @beers = Beer.where("name like ?", "%#{@beer_search}%").order(evaluation: :desc).page(params[:page]).per(10)
    elsif @refine_brewery != nil
      @beers = Beer.where(brewery_id: @refine_brewery).order(evaluation: :desc).page(params[:page]).per(10)
    elsif @refine_beer_style != nil
      @beers = Beer.where(beer_style_id: @refine_beer_style).order(evaluation: :desc).page(params[:page]).per(10)
    else
      @beers = Beer.order(evaluation: :desc).page(params[:page]).per(10)
    end
  end

  def show
    @beer = Beer.find(params[:id])
    @breweries = Brewery.all
    @beer_styles = BeerStyle.all
    @posts = @beer.posts.order(id: :desc).page(params[:page]).per(7)
    @bars = @beer.drunk_bars.distinct.order(place_name: :asc)
    # @beerが飲まれた（紐づけられた）お店のデータを取得し重複を排除、所在地の昇順で並べ替える
    @shops = @beer.purchased_shops.distinct.order(place_name: :asc)
    # @beerが買われた（紐づけられた）お店のデータを取得し重複を排除、所在地の昇順で並べ替える
    gon.bars = @beer.drunk_bars.distinct
    gon.shops = @beer.purchased_shops.distinct
  end

  def edit
    @beer = Beer.find(params[:id])
    @breweries = Brewery.all
    @beer_styles = BeerStyle.all
  end

  def update
    @beer = Beer.find(params[:id])
    @beer.update(beer_params) ? (redirect_to admin_beer_path(@beer), success: "ビール情報を更新しました") : (render "error")
  end

  def destroy
    @beer = Beer.find(params[:id])
    @beer.destroy
    redirect_to admin_beers_path, alert: "ビール情報を削除しました"
  end

  private
    def beer_params
      params.require(:beer).permit(:brewery_id, :beer_style_id, :name, :abv, :ibu, :description)
    end
end

app/helpers/admin/beers_helper.rb
module Admin::BeersHelper
end

app/views/admin/beers/_beer_form.html.erb
<div id="error-message">
  <%= render "layouts/errors", obj: beer %>
</div>

<%= form_with model: [:admin, beer], local: false do |f| %>
  <div class="row form-group my-2">
    <div class="col-md-3 pr-0">
      <%= f.label :name, "ビール名", class: "col-form-label" %><span class="text-danger">*</span>
    </div>
    <div class="col-md-9">
      <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "検索しやすいよう正式名称を入力しましょう！", class: "form-control rounded-pill" %>
    </div>
  </div>

  <div class="row form-group my-2">
    <div class="col-md-3 pr-0">
       <%= f.label :brewery_id, "ブルワリー", class: "col-form-label" %><span class="text-danger">*</span>
    </div>
    <div class="col-md-9">
      <%= f.collection_select :brewery_id, @breweries, :id, :name, {prompt: '--選択してください--'}, class: 'form-control rounded-pill' %>
    </div>
  </div>

  <div class="row form-group my-2">
    <div class="col-md-3 pr-0">
      <%= f.label :beer_style_id, "ビアスタイル", class: "col-form-label" %><span class="text-danger">*</span>
    </div>
    <div class="col-md-9">
      <%= f.collection_select :beer_style_id, @beer_styles, :id, :name, {prompt: '--選択してください--'}, class: 'form-control rounded-pill' %>
    </div>
  </div>

  <div class="row form-group my-2">
    <div class="col-md-3 pr-0 py-auto">
      <label for="abv", class="col-form-label">ABV<br><span class="small">（アルコール度数）</span></label>
    </div>
    <div class="col-md-2 my-auto pr-0">
        <%= f.text_field :abv, autofocus: true, autocomplete: "abv", placeholder: "省略可", class: "form-control rounded-pill" %>
    </div>
    <div class="col-md-1 pl-0 my-auto text-center">
      <span>%</span>
    </div>

    <div class="col-md-3 pr-0">
      <label for="ibu", class="col-form-label">IBU<br><span class="small">（国際苦味単位）</span></label>
    </div>
    <div class="col-md-3 my-auto">
      <%= f.text_field :ibu, autofocus: true, autocomplete: "ibu", placeholder: "省略可", class: "form-control rounded-pill" %>
    </div>
  </div>

  <div class="row form-group my-2">
    <div class="col-md-3 pr-0">
      <%= f.label :description, "ビールの説明", class: "col-form-label"  %>
    </div>
    <div class="col-md-9">
      <%= f.text_area :description, autofocus: true, rows: 5, placeholder: "省略可", class: "form-control" %>
    </div>
  </div>

  <div class="text-center py-3">
    <% unless params[:id] %>
      <%= f.submit "登録", class: "btn btn-success px-4 rounded-pill" %>
    <% else %>
    　<%= f.submit "更新", class: "btn btn-success px-4 rounded-pill" %>
    <% end %>
    <%# IDが取得されていなければ新規登録画面、取得されていれば編集画面と判断する %>
    <%= link_to "戻る", :back, class: "btn btn-primary px-4 rounded-pill" %>
  </div>
<% end %>

app/views/admin/beers/_beer_search.html.erb
<div class="form-row mt-3">
  <div class="col-md-4 pb-0">
    <%= form_with url: admin_beers_path, method: :get, local: false do |f| %>
      <div class="form-group input-group border border-secondary rounded-pill bg-white mb-1">
        <%= f.text_field :beer_search, placeholder: "ビール名で検索", class: "form-control form-control-sm input-group-prepend border-0 bg-transparent" %>
        <span class="input-group-btn">
          <%= f.button type: "submit", class: "border-0 form-control form-control-sm bg-transparent" do %><i class="fas fa-search"></i><% end %>
        </span>
      </div>
    <% end %>
  </div>

  <div class="col-md-4 pb-0">
    <%= form_with url: admin_beers_path, method: :get, local: false do |f| %>
      <div class="form-group input-group form-check pl-0 border border-secondary rounded-pill bg-white mb-1">
        <%= f.collection_select :refine_brewery, breweries, :id, :name, {prompt: 'ブルワリーから探す'}, class: 'form-control form-control-sm input-group-prepend border-0 bg-transparent' %>
        <span class="input-group-btn">
         <%= f.button type: "submit", class: "border-0 form-control form-control-sm bg-transparent" do %><i class="fas fa-search"></i><% end %>
        </span>
      </div>
    <% end %>
  </div>

  <div class="col-md-4 pb-0">
    <%= form_with url: admin_beers_path, method: :get, local: false do |f| %>
      <div class="form-group input-group form-check pl-0 border border-secondary rounded-pill bg-white mb-1">
        <%= f.collection_select :refine_beer_style, beer_styles, :id, :name, {prompt: 'ビアスタイルから探す'}, class: 'form-control form-control-sm input-group-prepend border-0 bg-transparent' %>
        <span class="input-group-btn">
         <%= f.button type: "submit", class: "border-0 form-control form-control-sm bg-transparent" do %><i class="fas fa-search"></i><% end %>
        </span>
      </div>
    <% end %>
  </div>
</div>

<div class="d-flex justify-content-between mt-3 mb-2">
  <span class="btn btn-light border-dark">
    <%= link_to "ビール情報作成", new_admin_beer_path, class:"text-reset" %>
  </span>
</div>

app/views/admin/beers/_index.html.erb
<% beers.each.with_index(1) do |beer, index| %>
<div class="card border-dark mt-3">
  <div class="card-body row">
    <div class="col-9">
      <div class="card-title mb-0">
        <h5 class="font-weight-bold d-inline-block mb-0">
          <% case index when 1 %>
            <span class="fa-layers">
              <i class="fas fa-crown fa-lg text-warning", data-fa-transform="left-4 up-1"></i>
              <span class="fa-layers-text", data-fa-transform="shrink-4">
                <%= index %>
              </span>
            </span>
          <% when 2 %>
            <span class="fa-layers">
              <i class="fas fa-crown fa-lg text-secondary", data-fa-transform="left-4 up-1"></i>
              <span class="fa-layers-text", data-fa-transform="shrink-4">
                <%= index %>
              </span>
            </span>
          <% when 3 %>
            <span class="fa-layers">
              <i class="fas fa-crown fa-lg color-orange", data-fa-transform="left-4 up-1"></i>
              <span class="fa-layers-text", data-fa-transform="shrink-4">
                <%= index %>
              </span>
            </span>
          <% end %>
          <%= link_to admin_beer_path(beer), class: "text-reset" do %>
            <%= beer.name %>
          <% end %></h5>
        <h6 class="d-inline-block mb-0"> / <%= beer.brewery.name %></h6>
      </div>
      <div class="border-bottom small"><%= beer.beer_style.name %></div>
      <div class="d-flex align-items-end">
        <% if beer.evaluation == nil %>
          <span>未評価</span>
        <% else %>
          <span id="beers-rate<%= beer.id %>">
            <%= render "public/beers/beer_rate_display", beer: beer %>
          </span>
          <span class="ml-2 font-weight-bold ">
            <%= beer.evaluation.round(2) %>
          </span>
        <% end %>
        <small>
          （<%= beer.posts.count %>件の投稿）
        </small>
      </div>
    </div>
    <div class="col-3 d-flex align-items-center justify-content-center">
      <%= link_to "編集", edit_admin_beer_path(beer), class: "btn btn-success" %>
      <%= link_to "削除", admin_beer_path(beer), method: :delete, "data-confirm" => "紐づく投稿も削除されます。本当に削除しますか？", class: "btn btn-danger ml-1" %>
    </div>
  </div>
</div>
<% end %>

<% if member_signed_in? %>
  <div class="text-center mt-2">
  <%= link_to admin_new_beer_path, class: "text-reset" do %>
    <u>投稿したいビールが見つかりませんか？<br>こちらから情報を追加しましょう！</u>
  <% end %>
  </div>
<% end %>

<div class="d-flex justify-content-center mt-2">
  <%= paginate beers %>
</div>

app/views/admin/beers/edit.html.erb
<div class="card border-dark mx-auto mt-3 col-md-8">
  <div class="card-body">
    <h5 class="card-title border-bottom pb-1 mb-3">ビール情報編集
      <span class="small text-danger"> *は必須項目です</span>
    </h5>

    <%= render "beer_form", beer: @beer %>

  </div>
</div>

app/views/admin/beers/error.js.erb
$("#error-message").html("<%= j(render 'layouts/errors', obj: @beer) %>");

app/views/admin/beers/index.html.erb
<div class="col-md-10 mx-auto">
  <%= render "beer_search", breweries: @breweries, beer_styles: @beer_styles %>
  <div id="beers-index">
    <%= render "index", beers: @beers %>
  </div>
</div>

app/views/admin/beers/index.js.erb
$("#beers-index").html("<%= j(render "public/beers/index", beers: @beers) %>");

if(<%= @beer_search != nil %>){
  $("#refine_brewery").val("");
  $("#refine_beer_style").val("");
}

if(<%= @refine_brewery != nil %>){
  $("#beer_search").val("");
  $("#refine_beer_style").val("");
}

if(<%= @refine_beer_style != nil %>){
  $("#beer_search").val("");
  $("#refine_brewery").val("");
}

<%# 何の検索結果かわかりやすくするため、検索に使用していないフォームをリセットする %>

app/views/admin/beers/new.html.erb
<div class="card border-dark mx-auto mt-3 col-md-8">
  <div class="card-body">
    <h5 class="card-title border-bottom pb-1 mb-3">ビール情報登録
      <span class="small text-danger"> *は必須項目です</span>
    </h5>

    <%= render "beer_form", beer: @beer %>

  </div>
</div>

app/views/admin/beers/show.html.erb
<div class="col-md-10 mx-auto">
  <div class="card border-dark my-3">
    <div class="card-body">
      <div class="border-bottom row">
        <div class="col-md-8">
          <div class="card-title mb-0">
            <h4 class="font-weight-bold d-inline-block mb-0">
              <%= @beer.name %>
            </h4>
            <h5 class="d-inline-block mb-0"> / <%= @beer.brewery.name %></h5>
          </div>

          <div>
            <div><%= @beer.beer_style.name %></div>
            <div>ADV : <%= @beer.abv %> / IBU : <%= @beer.ibu.floor if @beer.ibu != nil %></div>
            <div><%= @beer.description %></div>
          </div>
        </div>
        <div class="col-md-4 d-flex align-items-center justify-content-center">
          <%= link_to "編集", edit_admin_beer_path(@beer), class: "btn btn-success" %>
          <%= link_to "削除", admin_beer_path(@beer), method: :delete, "data-confirm" => "紐づく投稿も削除されます。本当に削除しますか？", class: "btn btn-danger ml-1" %>
        </div>
      </div>

      <div class="d-flex align-items-center justify-content-center mt-2">
        <% unless @beer.evaluation %>
        <%# 評価のカラムがnilの場合 %>
          <span>未評価</span>
        <% else %>
          <span id="beers-rate<%= @beer.id %>">
            <%= render "public/beers/beer_rate_display", beer: @beer %>
          </span>
          <span class="ml-2 font-weight-bold ">
            <%= @beer.evaluation.round(2) %>
          </span>
          <span>
            （<%= @beer.posts.count %>件の投稿）
          </span>
        <% end %>
      </div>
    </div>
  </div>

  <div class="d-flex justify-content-center">
    <%= link_to "戻る", admin_beers_path, class: "btn btn-primary px-4 rounded-pill" %>
  </div>

  <ul class="nav nav-tabs nav-justified mt-3" >
    <li class="nav-item">
      <a href="#beer-posts" class="nav-link active text-reset border-dark" data-toggle="tab">ビールについての投稿</a>
    </li>
    <li class="nav-item">
      <a href="#bars-list" class="nav-link text-reset border-dark" data-toggle="tab">飲まれたお店</a>
    </li>
    <li class="nav-item">
      <a href="#shops-list" class="nav-link text-reset border-dark" data-toggle="tab">買われたお店</a>
    </li>
  </ul>

  <div class="tab-content">
    <div id="beer-posts", class="tab-pane active">
      <%= render "admin/posts/index", posts: @posts %>
    </div>

    <div id="bars-list", class="tab-pane">
      <%= render "public/beers/bars_list", bars: @bars %>
    </div>

    <div id="shops-list", class="tab-pane">
      <%= render "public/beers/shops_list", shops: @shops %>
    </div>
  </div>
</div>

<%= render "public/beers/bar_map" %>