config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :beer_styles, except: [:show]
    resources :breweries, except: [:show]
    resources :members, except: [:new, :create] do
      get "followings" => "relationships#followings"
      get "followers" => "relationships#followers"
      get "group_list" => "groups#group_list"
    end
    resources :posts, except: [:new, :create] do
      resources :post_comments, only: [:destroy]
    end
    resources :beers
    resources :bars, only: [:index, :create, :destroy]
    resources :groups, except: [:new, :create] do
      resources :group_posts, except: [:new, :create] do
        resources :group_post_comments, only: [:destroy]
      end
    end
  end

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
    resources :beers, except: [:edit, :update, :destroy]
    resources :posts do
      resource :cheer, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :bars, only: [:create]
    resources :members, only: [:update, :index, :show] do
      resource :relationship, only: [:create, :destroy]
      get "followings" => "relationships#followings"
      get "followers" => "relationships#followers"
    end
    resources :groups do
      resource :groups_member, only: [:create, :destroy]
      resources :group_posts do
        resources :group_post_comments, only: [:create, :destroy]
      end
    end
    resources :message_rooms, only: [:create, :show, :index] do
     resource :entry, only: [:create]
     resources :messages, only: [:create, :destroy]
    end
    devise_scope :member do
      post "guest_sign_in", to: "members/sessions#guest_sign_in"
    end
    get "mypage" => "homes#timeline"
    get "mypage/cheers_list" => "homes#cheers_list"
    get "mypage/group_list" => "homes#group_list"
    get "mypage/edit" => "members#edit"
  end

  root "public/homes#top"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation", class="alert alert-danger" role="alert">
    <h5>入力内容を確認してください</h5>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-dark py-2 mt-3">
  <p class="text-center text-white">Copyright © 2022 Brew Hub All Rights Reserved.</p>
</footer>

<% unless flash.empty? %>
  <script>
    toastr.options = {
      "positionClass": "toast-top-left",
      "closeButton": true,
    };
    <% flash.each do |type, msg| %>
      <% type = 'info' if type == 'notice' %>
      <% type = 'error' if type == 'alert' %>
      <% type = 'success' if type == 'success' %>
      toastr['<%= type %>']('<%= msg %>');
    <% end %>
  </script>
<% end %>

app/views/layouts/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <span class="navbar-brand ml-3">
      <%= link_to root_path, class: "text-reset" do %>
        <%= image_tag asset_path("logo.png"), size: "200x44", class: "border border-dark m-0 p-0" %>
      <% end %>
    </span>

    <% if member_signed_in? %>
      <div class="ml-auto">
        <li class="nav-item dropdown list-unstyled">
            <a class="nav-link dropdown-toggle bg-transparent text-white" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag current_member.get_member_image(40,40), class: "rounded-circle image-fit" %>
              @<%= current_member.account_name %>
            </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "マイページ", mypage_path, class: "dropdown-item" %>
            <%= link_to "ログアウト", destroy_member_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </div>
    <% elsif admin_signed_in? %>
      <div class="ml-auto">
        <li class="nav-item dropdown list-unstyled">
            <a class="nav-link dropdown-toggle bg-transparent text-white" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              管理者としてログイン中
            </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <% if member_signed_in? %>
          <%= render "layouts/menu_member" %>
        <% elsif admin_signed_in? %>
          <%= render "layouts/menu_admin" %>
        <% else %>
          <%= render "layouts/menu_non_member" %>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_menu_admin.html.erb
<li class="nav-item mx-2 my-1 text-white text-center my-auto">
  <%= link_to admin_posts_path, class: "text-reset" do %><i class="fas fa-feather-alt"></i>投稿管理
</li><% end %>

<li class="nav-item dropdown list-unstyled text-center">
  <a class="nav-link dropdown-toggle bg-transparent text-white" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fas fa-wine-bottle"></i>情報管理
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
    <%= link_to "ビアスタイル", admin_beer_styles_path, class: "dropdown-item" %>
    <%= link_to "ブルワリー", admin_breweries_path, class: "dropdown-item" %>
    <%= link_to "お店", admin_bars_path, class: "dropdown-item" %>
    <%= link_to "ビール", admin_beers_path, class: "dropdown-item" %>
  </div>
</li>

<li class="nav-item dropdown list-unstyled text-center">
  <a class="nav-link dropdown-toggle bg-transparent text-white" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fas fa-user"></i>ユーザー管理
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
    <%= link_to "ユーザー", admin_members_path, class: "dropdown-item" %>
    <%= link_to "グループ", admin_groups_path, class: "dropdown-item" %>
  </div>
</li>

app/views/layouts/_menu_member.html.erb
<li class="nav-item mx-2 my-1 text-white text-center">
  <%= link_to beers_path, class: "text-reset" do %><i class="fas fa-beer"></i>ビールを探す
</li><% end %>

<li class="nav-item mx-2 my-1 text-white text-center">
  <%= link_to posts_path, class: "text-reset" do %><i class="fas fa-feather-alt"></i>投稿を探す
</li><% end %>

<li class="nav-item mx-2 my-1 text-white text-center">
  <%= link_to members_path, class: "text-reset" do %><i class="fas fa-user"></i>ユーザーを探す
</li><% end %>

<li class="nav-item mx-2 my-1 text-white text-center">
  <%= link_to groups_path, class: "text-reset" do %><i class="fas fa-users"></i>グループを探す
</li><% end %>

app/views/layouts/_menu_non_member.html.erb
<li class="nav-item mx-2 my-1 text-white text-center">
  <%= link_to beers_path, class: "text-reset" do %><i class="fas fa-beer"></i>ビールを探す
</li><% end %>

<li class="nav-item mx-2 my-1 text-white text-center">
  <%= link_to new_member_session_path, class: "text-reset" do %><i class="fas fa-sign-in-alt"></i>ログイン
</li><% end %>

<li class="nav-item mx-2 my-1 text-white text-center">
  <%= link_to new_member_registration_path, class: "text-reset" do %><i class="fas fa-user-plus"></i>会員登録
</li><% end %>

app/views/layouts/_mypage.html.erb
<div class="card border-dark mt-3 p-3">
  <div class="row">
    <div class="col-6 col-md-12 col-lg-6 mb-2">
      <%= image_tag current_member.get_member_image(150,150), class: "rounded-circle image-fit" %>
    </div>

    <div class="col-6 col-md-12 col-lg-6">
      <div class="font-weight-bold"><%= current_member.display_name %></div>
      <div class="small">@<%= current_member.account_name %></div>
      <div><i class="fas fa-beer text-warning"></i>
        <%= current_member.posts.count %>
        <span>Beers</span>
      </div>
      <div>
        <%= link_to member_followings_path(member_id: current_member.id), class: "text-reset" do %>
        <%= current_member.followings.count %><span class="small">フォロー</span>
        <% end %>
      </div>
      <div>
        <%= link_to member_followers_path(member_id: current_member.id), class: "text-reset" do %>
        <%= current_member.followers.count %><span class="small">フォロワー</span>
        <% end %>
      </div>
      <div>
        <%= link_to mypage_group_list_path, class: "text-reset" do %>
        <%= current_member.groups.count %><span class="small">グループ</span>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row py-2">
    <div class="col">
      <%= current_member.introduction %>
    </div>
  </div>

  <div class="row d-flex justify-content-center border-bottom px-2 pb-2">
    <%= link_to message_rooms_path, class:"col-lg btn btn-secondary m-1" do %><i class="far fa-envelope"></i>メッセージ<% end %>
    <%= link_to mypage_edit_path, class:"col-lg btn btn-secondary m-1" do %><i class="fas fa-wrench"></i>設定<% end %>
  </div>


  <% if current_member.posts.exists? %>
    <div class="row pt-2 pl-3">
      <u class="small text-secondary"><%= link_to "全ての投稿を見る", member_path(current_member.id), class: "text-reset" %></u>
    </div>

    <div class="row p-2">
    <% my_posts.each do |post| %>
     <%# @my_postsはアプリケーションコントローラで定義 %>
      <div class="col-4 p-1">
        <%= link_to post_path(post) do %>
          <%= image_tag post.get_post_image(150,150), class: "image-fit rounded" %>
        <% end %>
      </div>
      <% end %>
    </div>

  <% else %>
    <div class="row pt-2 pl-3">
      <span class="small">まだ投稿がありません<br>
      <u><%= link_to "ビールを探して投稿しましょう！", beers_path, class: "text-reset" %></u>
    </div>
  <% end %>
</div>

app/views/layouts/_sidebar.html.erb
<div class="col-md-2 mx-auto">
  <div class="card border-dark mt-3 p-2">
    <div class="font-weight-bold mx-auto my-2">
      Top Beers
    </div>

    <div class="pb-2" >
      <div class="small mb-1 pl-1">
        ■全ビール
      </div>

      <% if top_beer_all != nil %>
        <div class="d-flex">
          <div class="d-inline-box">
            <span class="fa-layers mt-2">
              <i class="fas fa-crown fa-2x text-warning", data-fa-transform="up-3 left-2 shrink-4"></i>
              <span class="fa-layers-text font-weight-bold", data-fa-transform="right-8 up-4 shrink-3">
                1
              </span>
            </span>
          </div>
          <div class="d-inline-box text-middle ml-3">
            <%= link_to top_beer_all.name, beer_path(top_beer_all), class: "text-reset" %>
          </div>
        </div>

        <div class="d-flex align-items-end justify-content-center border-bottoms">
          <% if top_beer_all.evaluation == nil %>
            <span class="mr-auto ml-2">未評価</span>
          <% else %>
            <span class="beers-rate-sidebar<%= top_beer_all.id %>">
              <%= render "public/beers/beer_rate_display", beer: top_beer_all %>
            </span>
            <span class="ml-2 font-weight-bold ">
              <%= top_beer_all.evaluation.round(2) %>
            </span>
          <% end %>
        </div>

      <% else %>
        <div class="small mb-1 pl-1">
          ビール情報がありません
        </div>
      <% end %>

    </div>
      <%= render "layouts/sidebar_content", top_beer: top_beer_1, my_beer_style: current_member.my_beer_style1_id %>
      <%= render "layouts/sidebar_content", top_beer: top_beer_2, my_beer_style: current_member.my_beer_style2_id %>
      <%= render "layouts/sidebar_content", top_beer: top_beer_3, my_beer_style: current_member.my_beer_style3_id %>
      <%= render "layouts/sidebar_content", top_beer: top_beer_4, my_beer_style: current_member.my_beer_style4_id %>

      <% if current_member.my_beer_style1_id.nil? ||
        current_member.my_beer_style2_id.nil? ||
        current_member.my_beer_style3_id.nil? ||
        current_member.my_beer_style4_id.nil? %>
      <div class="small border-top mb-1 p-1 pt-2">
        <span>設定されていないマイビアスタイルがあります</span><br>
        <u><%= link_to "こちらから設定しましょう！", mypage_edit_path, class: "text-reset" %></u>
      </div>
      <% end %>
  </div>
</div>

app/views/layouts/_sidebar_content.erb
<div class="border-top py-2" >
  <div class="small mb-1 pl-1">
    ■<%= top_beer.beer_style.name %>部門
  </div>
  <div class="d-flex">
    <div class="d-inline-box">
      <span class="fa-layers mt-2">
        <i class="fas fa-crown fa-2x text-warning", data-fa-transform="up-3"></i>
        <span class="fa-layers-text font-weight-bold", data-fa-transform="right-11 up-3">
          1
        </span>
      </span>
    </div>
    <div class="d-inline-box text-middle ml-4">
      <%= link_to top_beer.name, beer_path(top_beer), class: "text-reset" %>
    </div>
  </div>
  <div class="d-flex align-items-end border-bottoms">
    <% if top_beer.evaluation == nil %>
      <span>未評価</span>
    <% else %>
      <span class="beers-rate-sidebar<%= top_beer.id %>">
        <%= render "public/beers/beer_rate_display", beer: top_beer %>
      </span>
      <span class="ml-2 font-weight-bold ">
        <%= top_beer.evaluation.round(2) %>
      </span>
    <% end %>
  </div>
</div>

app/views/layouts/_sidebar_content.html.erb
<div class="border-top py-2" >
  <% if my_beer_style.nil? %>
    <div class="small mb-1 pl-1 ">
      <span>マイビアスタイルが設定されていません</span>
    </div>
  <% elsif top_beer != nil %>
    <div class="small mb-1 pl-1">
      ■<%= top_beer.beer_style.name %>部門
    </div>

    <div class="d-flex">
      <div class="d-inline-box">
        <span class="fa-layers mt-2">
          <i class="fas fa-crown fa-2x text-warning", data-fa-transform="up-3 left-2 shrink-4"></i>
          <span class="fa-layers-text font-weight-bold", data-fa-transform="right-8 up-4 shrink-3">
            1
          </span>
        </span>
      </div>
      <div class="d-inline-box text-middle ml-3">
        <%= link_to top_beer.name, beer_path(top_beer), class: "text-reset" %>
      </div>
    </div>

    <div class="d-flex align-items-end justify-content-center border-bottoms">
      <% if top_beer.evaluation == nil %>
        <span class="mr-auto ml-2">未評価</span>
      <% else %>
        <span class="beers-rate-sidebar<%= top_beer.id %>">
          <%= render "public/beers/beer_rate_display", beer: top_beer %>
        </span>
        <span class="ml-2 font-weight-bold ">
          <%= top_beer.evaluation.round(2) %>
        </span>
      <% end %>
    </div>

  <% else %>
    <div class="small mb-1 pl-1">
      <span>ビール情報がありません</span>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrewHub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= include_gon %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="sticky-top">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <span class="navbar-brand ml-3">
          <%= link_to root_path, class: "text-reset" do %>
            <%= image_tag asset_path("logo.png"), size: "200x44", class: "border border-dark m-0 p-0" %>
          <% end %>
        </span>

        <% if member_signed_in? %>
          <div class="ml-auto">
            <li class="nav-item dropdown list-unstyled">
                <a class="nav-link dropdown-toggle bg-transparent text-white" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= image_tag current_member.get_member_image(40,40), class: "rounded-circle image-fit" %>
                  @<%= current_member.account_name %>
                </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to "マイページ", mypage_path, class: "dropdown-item" %>
                <%= link_to "ログアウト", destroy_member_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          </div>
        <% end %>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if member_signed_in? %>
              <%= render "layouts/menu_member" %>
            <% else %>
              <%= render "layouts/menu_non_member" %>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <main>
      <div class="container-fluid">
        <div class="row">
          <% if member_signed_in? %>
            <%= render "layouts/mypage" %>
          <% end %>
          <div class="col-md-7 mx-auto">
            <%= yield %>
          </div>
          <% if member_signed_in? %>
            <%= render "layouts/sidebar" %>
          <% end %>
        </div>
      </div>
    </main>

    <footer class="bg-dark py-2">
      <p class="text-center text-white">Copyright © 2022 Brew Hub All Rights Reserved.</p>
    </footer>

    <% unless flash.empty? %>
        <script>
          toastr.options = {
            "positionClass": "toast-top-left",
            "closeButton": true,
          };
          <% flash.each do |type, msg| %>
            <% type = 'info' if type == 'notice' %>
            <% type = 'error' if type == 'alert' %>
            <% type = 'success' if type == 'success' %>
            toastr['<%= type %>']('<%= msg %>');
          <% end %>
        </script>
    <% end %>

  </body>
</html>

app/views/layouts/application_mypage.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrewHub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= include_gon %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <main>
      <div class="container-fluid">
        <div class="row">
          <% if member_signed_in? %>
            <div class="col-md-3">
              <%= render "layouts/mypage" %>
            </div>
          <% end %>
          <div class="col-md-7 mx-auto">
            <%= yield %>
          </div>
          <% if member_signed_in? %>
            <%= render "layouts/sidebar" %>
          <% end %>
        </div>
      </div>
    </main>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/application_no_sidebar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrewHub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= include_gon %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <main>
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-10 mx-auto">
            <%= yield %>
          </div>
        </div>
      </div>
    </main>

  <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/application_top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrewHub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="sticky-top">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <span class="navbar-brand"><%= link_to "Brew Hub", root_path, class: "text-reset" %></span>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if member_signed_in? %>
              <li class="nav-item btn btn-light mx-2">マイページ</li>
              <li class="nav-item btn btn-light mx-2"><%= link_to "ビールを探す", beers_path, class: "text-reset" %></li>
              <li class="nav-item btn btn-light mx-2"><%= link_to "投稿を探す", posts_path, class: "text-reset" %></li>
              <li class="nav-item btn btn-light mx-2">ユーザーを探す</li>
              <li class="nav-item btn btn-light mx-2">グループを探す</li>
              <li class="nav-item btn btn-light mx-2"><%= link_to "ログアウト", destroy_member_session_path, method: :delete, class: "text-reset" %></li>
            <% elsif admin_signed_in? %>
              <li class="nav-item btn btn-light mx-2"><%= link_to "ビアスタイル管理", admin_beer_styles_path, class: "text-reset" %></li>
              <li class="nav-item btn btn-light mx-2"><%= link_to "ブルワリー管理", admin_breweries_path, class: "text-reset" %></li>
              <li class="nav-item btn btn-light mx-2">ビール管理</li>
              <li class="nav-item btn btn-light mx-2">投稿管理</li>
              <li class="nav-item btn btn-light mx-2">ユーザー管理</li>
              <li class="nav-item btn btn-light mx-2">グループ管理</li>
              <li class="nav-item btn btn-light mx-2"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "text-reset" %></li>
            <% else %>
              <li class="nav-item btn btn-light mx-2">ビールを探す</li>
              <li class="nav-item btn btn-light mx-2"><%= link_to "ログイン", new_member_session_path, class: "text-reset" %></li>
              <li class="nav-item btn btn-light mx-2"><%= link_to "会員登録", new_member_registration_path, class: "text-reset" %></li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <div class="container-fluid">
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </main>

    <footer class="fixed-bottom bg-dark py-2">
      <p class="text-center text-white">Copyright © 2022 Brew Hub All Rights Reserved.</p>
    </footer>
  </body>
</html>